Error handling MobileClient.
Bnei-Baruch/galaxy3 pull request #180
Opened 2020-10-19 01:21 UTC by bbfsdev

2020-10-19 01:44 UTC, edoshor requested changes

2020-10-19 01:44 UTC, edoshor commented on src/apps/MobileApp/MobileClient.js
> +                captureException(error, {source: 'Videoroom'});
captureMessage not exception

2020-10-20 03:00 UTC, bbfsdev commented on src/apps/MobileApp/MobileClient.js
> +                captureException(error, {source: 'Videoroom'});
Fixed.

2020-10-20 23:59 UTC, edoshor approved these changes

2020-10-21 15:35 UTC, merged