Error handling AdminRoot.
Bnei-Baruch/galaxy3 pull request #181
Opened 2020-10-19 01:21 UTC by bbfsdev

2020-10-19 01:45 UTC, edoshor requested changes

2020-10-19 01:45 UTC, edoshor commented on src/apps/AdminApp/AdminRoot.js
> +            captureException(error, {source: 'AdminRoot'});
captureMessage, not exception

2020-10-20 03:00 UTC, bbfsdev commented on src/apps/AdminApp/AdminRoot.js
> +            captureException(error, {source: 'AdminRoot'});
Fixed.

2020-10-21 00:00 UTC, edoshor approved these changes

2020-10-21 15:35 UTC, merged